name: Issues Occurs
on: issues 

jobs:
    Output-failed:
        runs-on: ubuntu-latest
        steps:
        - name: Print out event details
          run: echo "My Result is ${{ toJson(github) }}"
