name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the deployable aerifact
                required: false
                default: dist
                type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v4
              with: 
                name: ${{ inputs.artifact-name }}
            - name: Output info
              run: echo "information Outputed ${{  runner.os }}"
