name: Deploy website
on:
  push:
    branches:
      - 'main'
env:

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
        - name: Get Code from Repo
          uses: actions/checkout@v4
        - name: Cache dependencies
          uses: actions/checkout@v4
          with: 
              path: ~/.npm
              key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        - name:  Install Dependencies
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Run Ci
          run: npm ci
        - name: Test and LINIt
          run: |
           npm test
           npm run lint
        - run: echo "Run Completed"

    Build:
          outputs:
            script-file:
          needs: Test
          runs-on: ubuntu-latest
          steps:
          - name: Get Code from Repo
            uses: actions/checkout@v4
          - name: Cache dependencies
            uses: actions/checkout@v4
            with: 
              path: ~/.npm
              key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          - name: Install Dependencies
            uses: actions/setup-node@v4
            with:
              node-version: 18
          - name: Run Ci
            run: |
             npm ci
             npm run build
          - run: echo "Deploying Project.."
          - name: Storing re-usable artifatcts
            uses: actions/upload-artifact@v4
            with:
              name: dist-files
              path: dist


    Deploy:
      needs: Build
      runs-on: ubuntu-latest
      steps:
        - name: Get Build Artifacts
          uses: actions/download-artifact@v4
          with: 
            name: dist-files
        - name: Output entire folder
          run: ls
        - name: Deploy application
          run: echo "Deploying application".....


